Repository greenbone/opensight-golang-libraries, pull requests merged in 2024-08, with the labels that each got.

#95 AT-1793: Add structured logging
  pkg/configReader/configReader.go
  pkg/dbcrypt/config/config.go
  pkg/dbcrypt/dbcrypt.go
  pkg/dbcrypt/dbcrypt_test.go
  pkg/jobQueue/jobQueue.go
  pkg/notifications/notification.go
  pkg/notifications/notification_test.go
  pkg/openSearch/openSearchClient/authenticator.go
  pkg/openSearch/openSearchClient/client.go
  pkg/openSearch/openSearchClient/config/config.go
  pkg/openSearch/openSearchClient/indexFunctions.go
  pkg/openSearch/openSearchClient/json.go
  pkg/openSearch/openSearchClient/opensearchProjectClient.go
  pkg/openSearch/openSearchClient/opensearchTestContainer.go
  pkg/openSearch/openSearchClient/updateQueue.go
  pkg/postgres/query/builder.go
  pkg/postgres/query/query.go
  pkg/postgres/query/query_test.go
  pkg/query/filter/validation.go
  pkg/query/paging/request_test.go
  pkg/retryableRequest/retryableRequest.go
  pkg/retryableRequest/retryableRequest_test.go
Labels: alpha release

#98 Fix use correct error variable in query builder
  pkg/postgres/query/builder.go
Labels: patch release

#94 change: provide current viewable paging results
  pkg/query/README.md
  pkg/query/paging/README.md
  pkg/query/paging/response.go
  pkg/query/responseWithMetadata.go
Labels: minor release

#107 Add: bool query option filter
  pkg/query/filter/request.go
  pkg/query/filter/type.go
  pkg/query/filter/type_enum.go
  pkg/query/filter/validation.go
  pkg/query/filter/validation_test.go
Labels: minor release
