Repository greenbone/opensight-golang-libraries, pull requests merged in 2024-06, with the labels that each got.

#60 add: add client for OpenSight Notification Service
  Makefile
  README.md
  go.mod
  go.sum
  pkg/notifications/README.md
  pkg/notifications/model.go
  pkg/notifications/notification.go
  pkg/notifications/notification_test.go
  pkg/postgres/query/README.md
  pkg/retryableRequest/retryableRequest.go
  pkg/retryableRequest/retryableRequest_test.go
Labels: minor release

#76 change: change postgres query builder string template to enhance security
  go.mod
  go.sum
  pkg/postgres/query/README.md
  pkg/postgres/query/builder.go
  pkg/postgres/query/builder_test.go
  pkg/postgres/query/compose.go
  pkg/postgres/query/query.go
Labels: alpha release

#72 At 521 enable authentication for opensearch
  go.mod
  go.sum
  pkg/openSearch/openSearchClient/README.md
  pkg/openSearch/openSearchClient/authenticator.go
  pkg/openSearch/openSearchClient/authenticator_test.go
  pkg/openSearch/openSearchClient/client.go
  pkg/openSearch/openSearchClient/config/config.go
  pkg/openSearch/openSearchClient/indexFunctions.go
  pkg/openSearch/openSearchClient/opensearchProjectClient.go
  pkg/openSearch/openSearchClient/updateQueue.go
Labels: alpha release

#77 add: implement additional postgres compare operators
  pkg/postgres/query/builder.go
  pkg/postgres/query/builder_test.go
  pkg/postgres/query/compose.go
  pkg/postgres/query/query.go
Labels: alpha release

#79 change: use postgres query builder field mapping for `ORDER BY`
  pkg/postgres/query/builder.go
  pkg/postgres/query/builder_test.go
Labels: patch release

#81 fix: adjust postgres paging query builder
  pkg/postgres/query/builder.go
  pkg/postgres/query/builder_test.go
Labels: patch release
