Repository greenbone/opensight-golang-libraries, pull requests merged in 2025-03, with the labels that each got.

#177 Omit empty keys field RequestField struct
  pkg/openSearch/openSearchClient/diskSpace.go
  pkg/query/filter/request.go
Labels: alpha release

#176 add: opensearch query builder - text contains operator (full text search)
  pkg/openSearch/openSearchQuery/README.md
  pkg/openSearch/openSearchQuery/boolQueryBuilder.go
  pkg/openSearch/openSearchQuery/compareHandler.go
  pkg/openSearch/openSearchQuery/compareHandler_test.go
  pkg/query/filter/type.go
  pkg/query/filter/type_enum.go
Labels: minor release

#179 refactor: add authentication to CreateNotification HTTP call
  pkg/notifications/notification.go
  pkg/notifications/notification_test.go
Labels: minor release

#185 Update: allow exists query on nested fields
  pkg/openSearch/openSearchQuery/boolQueryBuilder.go
  pkg/openSearch/openSearchQuery/compareHandler.go
Labels: patch release
